name: Deploy SRV

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_SRV_HOST }}
          username: ${{ secrets.DEPLOY_SRV_USER }}
          key: ${{ secrets.DEPLOY_SRV_KEY }}
          script: |
            set -e

            pwd
            ls -a

            echo "Changing to deployment folder..."
            cd /srv/auth-api

            echo "Pulling latest changes from main..."
            git fetch --all
            git reset --hard origin/main

            echo "Building updated containers..."
            docker compose build --pull

            echo "Recreating services..."
            docker compose up -d --remove-orphans

            echo "Pruning unused images..."
            docker image prune -f

            echo "Deployment finished successfully!"
